# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
#  title = "张锦山的个人主页"
#  [zh.params]
#    description = "这里是张锦山的个人主页"
#  [[zh.menu.main]]
#    name = "我"
#    url = "#about"
#    weight = 1
#
#  [[zh.menu.main]]
#    name = "首页"
#    url = "#about_zh"
#    weight = 10
#
#
#  [[zh.menu.main]]
#    name = "经历"
#    url = "#exp_zh"
#    weight = 30
#
#  [[zh.menu.main]]
#    name = "活动"
#    url = "#activities_zh"
#    weight = 40
#  
#  [[zh.menu.main]]
#    name = "荣誉"
#    url = "#honors_zh"
#    weight = 50
#
#  [[zh.menu.main]]
#    name = "简历"
#    url = "files/cv.pdf"
#    weight = 60
